apiVersion: v1
kind: Secret
metadata:
  name: plex-secrets
  namespace: plex
type: Opaque
stringData:
  SMB_USER: ''  ## Add your username
  SMB_PASS: ''  ## Add your password
  PLEX_CLAIM: '' ## Add your plex claim id