apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-ingressroute-cert
  namespace: plex # Optional but recommedned
spec:
  # Secret names are always required.
  secretName: plex-certificate-secret
  issuerRef:
    name: cloudflare-example-clusterissuer # This Must be configured for your cluster setup
    kind: ClusterIssuer # This Must be configured for your cluster setup
  dnsNames:
    - plex.example.com # This Must be configured for your cluster setup