apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ' ' # This Must be configured for your cluster setup
  resources:
    requests:
      storage: 5Gi
