# GATEWAY API SUPPORT - CILIUM
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  creationTimestamp: null
  name: plex-gateway
  namespace: plex # This Must be configured for your cluster setup
spec:
  gatewayClassName: cilium
  listeners:
  - hostname: plex.example.com # This Must be configured for your cluster setup
    name: plex-http
    port: 80
    protocol: HTTP
  - hostname: plex.example.com # This Must be configured for your cluster setup
    name: plex-https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - name: plex-certificate-secret
status: {}
