# GATEWAY API SUPPORT - HTTP ROUTE - CILIUM
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  creationTimestamp: null
  name: plex-ingress-https
  namespace: plex # This Must be configured for your cluster setup
spec:
  hostnames:
  - plex.example.com # This Must be configured for your cluster setup
  parentRefs:
  - name: plex-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: plex # This Must be configured for your cluster setup
      port: 32400